# Imported Necessary Libraries
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, TextAreaField, SubmitField
from wtforms.validators import DataRequired, Length, Email, EqualTo, Regexp, ValidationError
import os

# Created Registration Form Class
class RegistrationForm(FlaskForm):
    # User Information Fields
    userName = StringField('Username', validators=[DataRequired(message="Username Is Required"),Length(min=3, max=30, message="Username Must Be Between 3 And 30 Characters"),Regexp(r'^[A-Za-z_]+$', message="Username Must Contain Only Letters And Underscores")]) #Regex was Generated By Copilot
    email = StringField('Email', validators=[DataRequired(), Email(message="Invalid Email Address")])
    password = PasswordField('Password', validators=[DataRequired(message="Password Is Required"), Length(min=12, message="Password Must Be At Least 12 Characters Long"), Regexp(r'^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[^A-Za-z0-9])[^\s]+$', message="Password Must Have At Least One Uppercase Letter, One Lowercase Letter, One Digit, One Special Character, And No Spaces")]) #Regex was Generated By Copilot
    confirmPassword = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password', message="Passwords Must Match")])
    bioOrComment = TextAreaField('Bio Or Comment')
    submit = SubmitField('Register')
    
    # Function To Validate Username
    def validate_userName(self, field):
        reservedUsernames = {'admin', 'root', 'superuser'}
        if field.data and field.data.lower() in reservedUsernames:
            raise ValidationError("This Username Is Reserved")

    # Function To Validate Email
    def validate_email(self, field):
        allowedDomains = ('.edu', '.ac.uk', '.org')
        if field.data and not field.data.endswith(allowedDomains):
            raise ValidationError("Email Must End With .edu, .ac.uk, Or .org")
        
    # Function To Validate Passwords
    def validate_password(self, field):
        commonPasswords = {'password123', 'admin', 'qwerty', 'letmein', 'welcome', 'iloveyou', 'abc123', 'monkey', 'football'}
        if field.data and field.data.lower() in commonPasswords:
            raise ValidationError("Password Is Too Common")


