# Imported Necessary Libraries
from flask import Blueprint, render_template, request, redirect, url_for, current_app
from .forms import RegistrationForm
import bleach

# Blueprint
main = Blueprint('main', __name__)

# Home Route Redirecting to Registration
@main.route('/', methods=['GET'])
def home():
    return redirect(url_for('main.register'))

# Helper Function to Get User IP Address
def getUserIpAddress():
    if 'X-Forwarded-For' in request.headers:
        return request.headers.get('X-Forwarded-For').split(',')[0].strip()
    return request.remote_addr or 'unknown'

# Registration Route
@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegistrationForm()
    name = ''
    userIpAddress = getUserIpAddress()
    appLogger = current_app.logger

    # Handle Form Submission
    if request.method == 'POST':
        form.process(request.form)
        name = request.form.get('name', '')

        reservedUsernames = {'admin', 'root', 'superuser'}
        username = form.userName.data if hasattr(form, 'userName') else ''

        # Generated By Copilot
        bio = form.bioOrComment.data or ''
        allowedTags = ['b', 'i', 'u', 'em', 'strong', 'a', 'p', 'br', 'ul', 'ol', 'li']
        cleanBio = bleach.clean(bio, tags=allowedTags, attributes={'a': ['href', 'title']}, strip=True)

        # Log Any Changes Made By The Sanitizer
        if cleanBio != bio:
            appLogger.warning(
                "Bio Sanitized - Client_Ip=%s Username=%s Original_Snippet=%s Sanitized_Snippet=%s",
                userIpAddress,
                username,
                (bio[:200] if bio else ''),
                (cleanBio[:200] if cleanBio else ''),
            )

        bio = cleanBio
        
        # Checking Reserved Usernames
        if form.validate():

            if username and username.lower() in reservedUsernames:
                appLogger.warning("Attempt To Register Reserved Username - Client_Ip=%s Username=%s", userIpAddress, username)
            else:

                appLogger.info("Registration Successful - Client_Ip=%s Username=%s Email=%s", userIpAddress, username, form.email.data)

                return render_template('register.html', form=form, success=True, username=username, bio=bio)
        else:

            errorsList = []
            for field, fieldErrors in form.errors.items():
                for error in fieldErrors:
                    errorsList.append(f"{field}: {error}")
            errorDetails = '; '.join(errorsList)
            appLogger.warning("Registration Validation Failed - Client_Ip=%s Username=%s Errors=%s", userIpAddress, username, errorDetails)

    return render_template('register.html', form=form, success=False, username=name)