# Imported Libraries
from typing import Optional
import bleach
from markupsafe import Markup, escape
from jinja2 import Environment, FileSystemLoader, select_autoescape

# Try To Import Bleach
try:
except Exception:  
    bleach = None

# Constants
ALLOWED_TAGS = ["b", "i", "u", "em", "strong", "a", "p", "ul", "ol", "li"]
ALLOWED_ATTRIBUTES = {"a": ["href", "title"]}
ALLOWED_PROTOCOLS = ["http", "https", "mailto"]


#Generated By Copilot
# Function To Sanitise HTML Input
def sanitiseHTML(rawHTML: Opt
                 ional[str]) -> Markup:
    if not rawHTML:
        return Markup("")

    if bleach is None:
        return Markup(escape(rawHTML))

    cleaned = bleach.clean(
        rawHTML,
        tags=ALLOWED_TAGS,
        attributes=ALLOWED_ATTRIBUTES,
        protocols=ALLOWED_PROTOCOLS,
        strip=True,
    )

    linker = bleach.linkifier.Linker(callbacks=[bleach.callbacks.nofollow, bleach.callbacks.target_blank])
    cleaned = linker.linkify(cleaned)

    return Markup(cleaned)

# Function To Sanitise Bio Or Comment Input
def sanitiseBioComment(bioText: Optional[str]) -> Markup:
    return sanitiseHTML(bioText)

# Function To Create Jinja2 Environment
def create_jinja_environment(templateFolder: str) -> Environment:
    loader = FileSystemLoader(templateFolder)
    env = Environment(
        loader=loader,
        autoescape=select_autoescape(enabledExtensions=("html", "htm", "xml")),
    )
    return env